# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class TimeInterval(str, Enum):
    year = "year"
    month = "month"
    week = "week"
    day = "day"
    hour = "hour"


class PatrolEventsBarChart1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    time_interval: TimeInterval = Field(..., title="Time Interval")


class PatrolEventsBarChart(BaseModel):
    patrol_events_bar_chart: PatrolEventsBarChart1 | None = Field(
        None, title="Draw Time Series Bar Chart for Patrols Events"
    )


class SMARTConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TemporalGrouper(str, Enum):
    field_Y = "%Y"
    field_B = "%B"
    field_Y__m = "%Y-%m"
    field_j = "%j"
    field_d = "%d"
    field_A = "%A"
    field_H = "%H"
    field_Y__m__d = "%Y-%m-%d"


class ValueGrouper(RootModel[str]):
    root: str = Field(..., title="Category")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: confloat(ge=0.001) | None = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: confloat(gt=0.001) | None = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: confloat(ge=1.0) | None = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: confloat(gt=1.0) | None = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: confloat(gt=0.001) | None = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: confloat(gt=0.001) | None = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class BoundingBox(BaseModel):
    min_y: float | None = Field(-90.0, title="Min Latitude")
    max_y: float | None = Field(90.0, title="Max Latitude")
    min_x: float | None = Field(-180.0, title="Min Longitude")
    max_x: float | None = Field(180.0, title="Max Longitude")


class Coordinate(BaseModel):
    y: float = Field(..., description="Example -0.15293", title="Latitude")
    x: float = Field(..., description="Example 37.30906", title="Longitude")


class AutoScaleOrCustom(str, Enum):
    Auto_scale = "Auto-scale"


class AutoScaleGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Auto-scale"] = Field(
        "Auto-scale", title="Grid Cell Size"
    )


class AutoScaleOrCustom1(str, Enum):
    Customize = "Customize"


class CustomGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Customize"] = Field(
        "Customize", title="Grid Cell Size"
    )
    grid_cell_size: confloat(lt=10000.0, gt=0.0) | None = Field(
        5000,
        description="Define the resolution of the raster grid (in the unit of measurement defined by the coordinate reference system set below). A smaller grid cell size provides more detail, while a larger size generalizes the data.",
        title="Custom Grid Cell Size",
    )


class SmartClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: SMARTConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[ValueGrouper | TemporalGrouper] | None = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class PatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: TrajectorySegmentFilter | None = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class PreprocessPatrolObservations(BaseModel):
    patrol_traj: PatrolTraj | None = Field(
        None, title="Transform Relocations to Trajectories"
    )


class FilterPatrolEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: BoundingBox | None = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_y": -90.0, "max_y": 90.0, "min_x": -180.0, "max_x": 180.0}
        ),
        description="Filter events to inside these bounding coordinates.",
        title="Bounding Box",
    )
    filter_point_coords: list[Coordinate] | None = Field(
        default_factory=list,
        description="By adding a filter, the workflow will not include events recorded at the specified coordinates.",
        title="Filter Exact Point Coordinates",
    )
    reset_index: bool | None = Field(
        True, description="Reset index after filtering", title="Reset Index"
    )


class PreprocessPatrolEvents(BaseModel):
    filter_patrol_events: FilterPatrolEvents | None = Field(
        None, title="Apply Coordinate Filter"
    )


class Td(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    auto_scale_or_custom_cell_size: (
        AutoScaleGridCellSize | CustomGridCellSize | None
    ) = Field(
        default_factory=lambda: AutoScaleGridCellSize.model_validate(
            {"auto_scale_or_custom": "Auto-scale"}
        ),
        title="Grid Cell Size",
    )
    max_speed_factor: float | None = Field(
        1.05,
        description="An estimate of the subject's maximum speed as a factor of the maximum measured speed value in the dataset.",
        title="Max Speed Factor (Kilometers per Hour)",
    )
    expansion_factor: float | None = Field(
        1.05,
        description="Controls how far time density values spread across the grid, affecting the smoothness of the output.",
        title="Shape Buffer Expansion Factor",
    )


class TimeDensityMap(BaseModel):
    td: Td | None = Field(None, title="Calculate Time Density from Trajectory")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    smart_client_name: SmartClientName | None = Field(
        None, title="Select Smart Connection"
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    groupers: Groupers | None = Field(None, title="Group Data")
    Preprocess_patrol_observations: PreprocessPatrolObservations | None = Field(
        None,
        alias="Preprocess patrol observations",
        description="Preprocess patrol observations from EarthRanger.",
    )
    Preprocess_patrol_events: PreprocessPatrolEvents | None = Field(
        None,
        alias="Preprocess patrol events",
        description="Preprocess patrol events from EarthRanger.",
    )
    Patrol_events_bar_chart: PatrolEventsBarChart | None = Field(
        None,
        alias="Patrol events bar chart",
        description="Create the patrol events bar chart.",
    )
    Time_Density_Map: TimeDensityMap | None = Field(
        None,
        alias="Time Density Map",
        description="Calculate time density from patrol trajectories and display it on a map.",
    )
